// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkFeedExistenceByName = `-- name: CheckFeedExistenceByName :one
SELECT EXISTS (SELECT 1 FROM "feed" WHERE "name" = $1)
`

func (q *Queries) CheckFeedExistenceByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFeedExistenceByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO "feed"
    (user_id, name, url)
VALUES
    ($1, $2, $3)
RETURNING id, user_id, name, url, created_at, updated_at
`

type CreateFeedParams struct {
	UserID uuid.UUID
	Name   string
	Url    string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.UserID, arg.Name, arg.Url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedById = `-- name: GetFeedById :one
SELECT id, user_id, name, url, created_at, updated_at FROM "feed" WHERE id = $1
`

func (q *Queries) GetFeedById(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedById, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedListSortedByCreation = `-- name: GetFeedListSortedByCreation :many
SELECT id, user_id, name, url, created_at, updated_at FROM "feed" ORDER BY "feed"."created_at"
`

func (q *Queries) GetFeedListSortedByCreation(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedListSortedByCreation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
