// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPostsByUserFeedFollowsPaginated = `-- name: GetPostsByUserFeedFollowsPaginated :many
SELECT post.id, post.created_at, post.updated_at, post.title, post.url, post.description, post.published_at, post.feed_id, f.id, f.user_id, f.name, f.url, f.created_at, f.updated_at, f.last_fetched_at FROM "post"
    JOIN public.feed f on f.id = post.feed_id
    JOIN public.feed_follow ff on f.id = ff.feed_id
    JOIN public."user" u on u.id = ff.user_id
    WHERE u.id = $1
    LIMIT $2
    OFFSET $3
`

type GetPostsByUserFeedFollowsPaginatedParams struct {
	ID     uuid.UUID
	Limit  int32
	Offset int32
}

type GetPostsByUserFeedFollowsPaginatedRow struct {
	Post Post
	Feed Feed
}

func (q *Queries) GetPostsByUserFeedFollowsPaginated(ctx context.Context, arg GetPostsByUserFeedFollowsPaginatedParams) ([]GetPostsByUserFeedFollowsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUserFeedFollowsPaginated, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByUserFeedFollowsPaginatedRow
	for rows.Next() {
		var i GetPostsByUserFeedFollowsPaginatedRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.Post.Title,
			&i.Post.Url,
			&i.Post.Description,
			&i.Post.PublishedAt,
			&i.Post.FeedID,
			&i.Feed.ID,
			&i.Feed.UserID,
			&i.Feed.Name,
			&i.Feed.Url,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
			&i.Feed.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsCountByUserFeedFollows = `-- name: GetPostsCountByUserFeedFollows :one
SELECT COUNT(*) FROM "post"
    JOIN public.feed f on f.id = post.feed_id
    JOIN public.feed_follow ff on f.id = ff.feed_id
    JOIN public."user" u on u.id = ff.user_id
    WHERE u.id = $1
`

func (q *Queries) GetPostsCountByUserFeedFollows(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostsCountByUserFeedFollows, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertPostOnUrl = `-- name: UpsertPostOnUrl :exec
INSERT INTO "post"
    (title, url, description, published_at, feed_id)
    VALUES
    ($1, $2, $3, $4, $5)
    ON CONFLICT (url) DO NOTHING
`

type UpsertPostOnUrlParams struct {
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) UpsertPostOnUrl(ctx context.Context, arg UpsertPostOnUrlParams) error {
	_, err := q.db.ExecContext(ctx, upsertPostOnUrl,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}
